// Moodboard « ce qui est beau » (2026-10-07) : 20 références réelles, rangées en 7 familles visuelles.
// Les captures viennent de pages publiques (fichiers public/demo/references/NN-id.jpg, recadrées pour
// masquer les bandeaux de cookies). Les palettes sont relevées sur ces captures, à 2 ou 3 teintes près.
// La preuve « plébiscité » ne cite que ce qui a été trouvé dans les sources indiquées ; sinon elle le dit.

export const FAMILIES = [
  {
    key: 'editorial',
    title: 'Clair éditorial chaud',
    blurb: 'Fond crème ou papier, serif de titre, accents sourds : un outil qui a l’allure d’un livre bien composé plutôt que d’un logiciel.',
  },
  {
    key: 'suisse',
    title: 'Clair minimal suisse',
    blurb: 'Presque blanc, beaucoup d’air, une seule police, quelques pointes de couleur : la précision d’un instrument, sans décor.',
  },
  {
    key: 'pastel',
    title: 'Couleurs franches et pastel',
    blurb: 'Fond blanc mais des couleurs de catégorie vives et douces à la fois, qui rendent un agenda lisible et joyeux.',
  },
  {
    key: 'arc',
    title: 'Dégradés vifs façon Arc',
    blurb: 'Un aplat ou un dégradé saturé en fond de page, une interface blanche posée dessus : l’énergie d’une marque, pas d’un outil gris.',
  },
  {
    key: 'sombre',
    title: 'Sombre premium',
    blurb: 'Noir profond, filets fins, lumière qui vient d’un seul accent : l’esprit des outils de développeurs et de productivité.',
  },
  {
    key: 'retro',
    title: 'Rétro instrument et objet',
    blurb: 'L’interface pensée comme un objet physique : cadran, matrice de points, pixels, couleur de boîtier. Le plus proche de ton goût pour l’automobile des années 70.',
  },
  {
    key: 'matiere',
    title: 'Matière, photo et sombre éditorial',
    blurb: 'Du sombre qui n’est pas du noir : brun, bleu nuit, photographie, tranches de livres. La profondeur vient de la matière.',
  },
];

export const REFS = [
  {
    n: 1,
    id: 'claude',
    family: 'editorial',
    name: 'Claude (Anthropic)',
    url: 'https://claude.com/',
    image: '/demo/references/01-claude.jpg',
    palette: ['#FAF9F5', '#C8C7C3', '#43433F', '#141413', '#D97757'],
    typo: 'Anthropic Serif (titres), Anthropic Sans (texte), Anthropic Mono : polices maison',
    why: 'Un fond parchemin, un titre en serif généreux et un seul orange terre cuite réservé à l’étoile : l’écran se lit comme une page de livre. Les boutons sont noirs, arrondis, sans ombre : le calme vient de la retenue.',
    transposable: 'Fond crème au lieu de gris ou de blanc pur, serif pour le titre du jour et les en-têtes de colonnes, une seule couleur d’accent rare (par exemple pour « maintenant » dans l’agenda).',
    proof: 'Identité conçue par l’agence Geist (couleur « Clay » #D97757, serif maison) ; l’analyse de DesignRush la décrit comme faite pour « ne ressembler à aucun rival IA ».',
    proofUrl: 'https://www.designrush.com/best-designs/logo/claude-logo-design-the-ai-mark-built-to-look-none-of-its-rivals',
  },
  {
    n: 2,
    id: 'sunsama',
    family: 'editorial',
    name: 'Sunsama',
    url: 'https://www.sunsama.com/',
    image: '/demo/references/02-sunsama.jpg',
    palette: ['#FFFFFF', '#FAF6F4', '#FEE1CA', '#FEB54D', '#A181FE', '#67C1F3'],
    typo: 'DM Sans (titres et texte), Outfit en accent',
    why: 'Un dégradé pêche très pâle autour d’un planificateur journalier en colonnes, dont les blocs prennent des couleurs douces (orange, violet, bleu). L’interface est dense mais respire parce que les couleurs restent claires et chaudes.',
    transposable: 'Le plus proche de Cadran fonctionnellement : colonnes de jours, tâches dans des blocs colorés, ton calme. Reprendre les teintes pastel chaudes pour les catégories plage et tâche.',
    proof: 'Recommandé par le Wirecutter du New York Times comme meilleur outil pour planifier sa journée (indiqué par Sunsama sur son site) ; entreprise Y Combinator W19.',
    proofUrl: 'https://www.sunsama.com/llms.txt',
  },
  {
    n: 3,
    id: 'craft',
    family: 'editorial',
    name: 'Craft',
    url: 'https://www.craft.do/',
    image: '/demo/references/03-craft.jpg',
    palette: ['#F6F6F6', '#A4D7F0', '#89CAEA', '#FDE492', '#5670AC', '#1C1C1C'],
    typo: 'Inter (interface), Source Serif 4 et Untitled Serif (titres)',
    why: 'Un collage de papier déchiré sur ciel bleu, un titre en serif fin et une application aux cartes de couleur pastel : de l’artisanat visible, qui change des dégradés numériques. Le serif donne une voix à l’outil.',
    transposable: 'Cartes aux couleurs de papier pour les blocs de l’agenda, titres en serif, éventuellement une texture de papier très discrète en fond de la colonne « À ranger ».',
    proof: 'Apple Design Award 2021 et « Mac App of the Year » aux App Store Awards 2021 ; German Design Award.',
    proofUrl: 'https://www.businesswire.com/news/home/20211202005370/en/Craft-Docs-Wins-Mac-App-of-the-Year-for-Apples-2021-App-Store-Awards',
  },
  {
    n: 4,
    id: 'amie',
    family: 'suisse',
    name: 'Amie',
    url: 'https://amie.so/',
    image: '/demo/references/04-amie.jpg',
    palette: ['#F9F9F9', '#D0D5D8', '#08A5FD', '#F3877E', '#030303'],
    typo: 'Inter, avec Averia Serif Libre en accent',
    why: 'Très épuré : un titre noir gras, un seul bouton bleu vif et un aperçu d’agenda aux ombres légères. Les touches de couleur (bleu, corail) apparaissent seulement là où il faut agir.',
    transposable: 'Hiérarchie par le seul poids de la police, boutons d’action en bleu vif sur fond presque blanc, ombres très douces pour sortir les cartes du fond.',
    proof: '#1 Produit du jour sur Product Hunt en 2022, en janvier 2024 (1,3 k votes) et en mai 2025 ; l’interface y est qualifiée de « belle » par la communauté.',
    proofUrl: 'https://www.hunted.space/product/amie-2/launches/amie-5',
  },
  {
    n: 5,
    id: 'attio',
    family: 'suisse',
    name: 'Attio',
    url: 'https://attio.com/',
    image: '/demo/references/05-attio.jpg',
    palette: ['#FFFFFF', '#F4F5FA', '#8BB0EB', '#E8AE42', '#6DD4AE', '#1A1A1A'],
    typo: 'Inter et Inter Display, Tiempos Text, JetBrains Mono',
    why: 'Blanc pur, titre noir massif, un bandeau noir en tête et un dégradé bleu tout en bas : la sobriété d’un tableur bien tenu, avec un peu de couleur en réserve. La densité de l’app (tableaux, barres latérales) reste lisible grâce aux filets très clairs.',
    transposable: 'Filets gris très clairs au lieu de cartes lourdes, grosse typographie sur les chiffres clés, tableaux denses pour les mails et la liste « À ranger ».',
    proof: '#1 Produit du jour sur Product Hunt (mars 2023, 668 votes) ; note de 5 sur 5 sur 41 avis, avec une interface citée comme moderne et intuitive.',
    proofUrl: 'https://www.hunted.space/product/attio/launches/attio-2',
  },
  {
    n: 6,
    id: 'vercel',
    family: 'suisse',
    name: 'Vercel',
    url: 'https://vercel.com/',
    image: '/demo/references/06-vercel.jpg',
    palette: ['#F9F9F9', '#DADAD9', '#868686', '#090909'],
    typo: 'Geist Sans et Geist Mono (créées avec Basement Studio, libres)',
    why: 'Gris à peine teinté, noir franc, aucun décor : le titre « Agentic Infrastructure » et deux boutons suffisent. C’est le minimalisme suisse poussé à l’extrême, où la typographie fait tout.',
    transposable: 'Palette quasi monochrome avec des pastilles de statut très petites, police mono pour les heures et les identifiants. Attention : Geist est déjà la police de la charte Graphite que tu as écartée, c’est le style de la page qui compte ici.',
    proof: 'Geist s’inspire du design suisse et « est devenue un hit chez les designers » (récit de Basement Studio, qui l’a dessinée avec Vercel).',
    proofUrl: 'https://basement.studio/post/the-birth-of-geist-a-typeface-crafted-for-the-web',
  },
  {
    n: 7,
    id: 'things',
    family: 'suisse',
    name: 'Things 3',
    url: 'https://culturedcode.com/things/',
    image: '/demo/references/07-things.jpg',
    palette: ['#F1F5F8', '#94A7C3', '#3580F3', '#123F89'],
    typo: 'Police système Apple (à vérifier : le CSS du site ne la déclare pas)',
    why: 'Fond bleu gris très pâle et icône bleue : l’apparence d’une app native Apple, calme et sans surcharge. Les cases à cocher, la liste et le tiroir « Aujourd’hui » sont dessinés avec une précision d’horloger.',
    transposable: 'Cocher une tâche avec un vrai geste satisfaisant, listes aérées avec une seule couleur d’accent, titres de sections discrets.',
    proof: 'Apple Design Award en 2009 puis en 2017 pour Things 3 : Apple le juge « clair et simple » et « un régal pour l’œil ».',
    proofUrl: 'https://en.wikipedia.org/wiki/Things_(software)',
  },
  {
    n: 8,
    id: 'notioncal',
    family: 'pastel',
    name: 'Notion Calendar (ex Cron)',
    url: 'https://www.notion.com/product/calendar',
    image: '/demo/references/08-notioncal.jpg',
    palette: ['#FFFFFF', '#F8F4F0', '#ED9461', '#BD8BFA', '#BADAE5', '#4C4242'],
    typo: 'Inter (NotionInter), Lyon Text (serif), iA Writer Mono',
    why: 'Un agenda blanc dont les événements ont des couleurs pastel nettes (orange, violet, bleu glacier) et des icônes flottantes en pastel. L’ensemble garde un quadrillage fin, très calendrier suisse, mais avec de la bonne humeur.',
    transposable: 'Directement le cas de Cadran : catégories d’événements en pastel saturé sur fond blanc, quadrillage fin des heures, vue semaine et mois.',
    proof: 'Cron, avant son rachat par Notion, a été désigné « Productivity App of the Year » 2021 et « Best Design in a Calendar App » 2022 (d’après le blog de Cron, donc auto-déclaré).',
    proofUrl: 'https://cron.com/blog/2022-11-04-best-design-in-a-calendar-app',
  },
  {
    n: 9,
    id: 'family',
    family: 'pastel',
    name: 'Family (portefeuille crypto)',
    url: 'https://family.co/',
    image: '/demo/references/09-family.jpg',
    palette: ['#FFFFFF', '#63C6FE', '#01B1FE', '#FECD6E', '#6A3727', '#E4EDE9'],
    typo: 'Police maison « Family » (LFE Sans) et Inter',
    why: 'Des personnages en 3D rondouillards, bleu ciel, jaune, brun chocolat, sur fond blanc : un produit sérieux (de l’argent) présenté avec de la tendresse. Les formes très arrondies donnent l’impression d’objets qu’on peut prendre en main.',
    transposable: 'Peu de choses directes pour un agenda, mais l’idée des illustrations comme état vide (« Tout est rangé ») et des formes très arrondies pour les boutons.',
    proof: 'Aucun prix trouvé ; l’interface mobile est décrite comme « lisse, avec une UI personnalisée de grande qualité » (AlternativeTo). À prendre comme goût partagé dans la communauté design, pas comme distinction.',
    proofUrl: 'https://alternativeto.net/software/family--crypto-wallet/about',
  },
  {
    n: 10,
    id: 'arc',
    family: 'arc',
    name: 'Arc (The Browser Company)',
    url: 'https://arc.net/',
    image: '/demo/references/10-arc.jpg',
    palette: ['#F6F6F5', '#3D45F8', '#7C80F4', '#63A3D4', '#252525'],
    typo: 'Marlin Soft SQ, Exposure (variable), ABC Favorit Mono, Inter',
    why: 'Un bleu électrique en aplat avec un liseré dentelé, un titre en serif posé sur dégradé pastel : l’interface est un jouet bien fait. La marque ose la couleur là où les navigateurs sont gris.',
    transposable: 'Chaque espace ou domaine de Cadran peut avoir sa couleur d’ambiance (comme les espaces d’Arc), sidebar teintée, aplats francs au lieu d’un gris neutre.',
    proof: 'Référence de la barre latérale verticale et des « espaces » colorés ; analyses de TechRepublic et de Contrary Research. Aucun prix de design vérifié ; Arc a depuis été mis en pause au profit de Dia.',
    proofUrl: 'https://www.techrepublic.com/article/arc-browser-review/',
  },
  {
    n: 11,
    id: 'dia',
    family: 'arc',
    name: 'Dia (The Browser Company)',
    url: 'https://www.diabrowser.com/',
    image: '/demo/references/11-dia.jpg',
    palette: ['#FAF7E8', '#FDC82D', '#DAA515', '#EACE7E', '#000000'],
    typo: 'Exposure (variable, serif d’affichage), ABC Oracle, ABC Favorit Mono',
    why: 'Un jaune moutarde plein écran, un gigantesque « DIA » en serif découpé dans la page, et une fenêtre d’app blanche posée dessus : de l’audace avec une seule couleur. Le contraste serif et interface minimale est très mémorable.',
    transposable: 'Une couleur dominante par page importante (écran de rangement forcé, page de démarrage) plutôt que du gris partout ; titres d’écran en grand serif.',
    proof: 'Lancé en bêta en juin 2025 par The Browser Company comme successeur d’Arc (TechCrunch). Aucun prix de design trouvé : reconnaissance par la presse tech.',
    proofUrl: 'https://techcrunch.com/2025/06/11/the-browser-company-launches-its-ai-first-browser-dia-in-beta',
  },
  {
    n: 12,
    id: 'linear',
    family: 'sombre',
    name: 'Linear',
    url: 'https://linear.app/',
    image: '/demo/references/12-linear.jpg',
    palette: ['#08090A', '#161719', '#363738', '#8A8F98', '#5E6AD2'],
    typo: 'Inter Display (Inter variable) : non lisible dans le CSS du site, à vérifier',
    why: 'Noir presque absolu, panneaux gris très sombres séparés par des filets à peine visibles, texte gris clair et un seul accent indigo. La densité est maximale sans bruit visuel, c’est la référence de l’interface d’outil sombre.',
    transposable: 'Seulement si tu veux du sombre : filets et hiérarchie par le gris, raccourcis clavier affichés. Attention : très proche de ce que tu as rejeté avec Graphite.',
    proof: 'Selon 925 Studios, il y a « une chance sur deux » que tout nouveau produit SaaS lancé ces deux dernières années lui ressemble ; saasframe.io catalogue ses pages comme exemples.',
    proofUrl: 'https://www.925studios.co/blog/linear-design-breakdown-saas-ui-2026',
  },
  {
    n: 13,
    id: 'raycast',
    family: 'sombre',
    name: 'Raycast',
    url: 'https://www.raycast.com/',
    image: '/demo/references/13-raycast.jpg',
    palette: ['#07080A', '#221218', '#A5394E', '#D37385', '#C62A35'],
    typo: 'Inter, Instrument Serif, JetBrains Mono (VT323 pour les accents pixel)',
    why: 'Des rubans rouge et rose en 3D sur noir profond, titre blanc très gros : la couleur est concentrée dans une seule image spectaculaire, le reste est silence. On sent une marque qui assume son goût.',
    transposable: 'Un visuel d’accent (rubans, forme abstraite) pour l’écran de rangement forcé ou l’accueil ; couleurs profondes, rouge utilisé comme lumière.',
    proof: '#1 Produit du jour sur Product Hunt le 30 novembre 2021 (528 votes) pour son API et son store ; nouveau #5 en février 2023 pour Raycast AI.',
    proofUrl: 'https://www.hunted.space/product/raycast/launches/raycast-api-and-store',
  },
  {
    n: 14,
    id: 'superhuman',
    family: 'sombre',
    name: 'Superhuman',
    url: 'https://superhuman.com/',
    image: '/demo/references/14-superhuman.jpg',
    palette: ['#161313', '#26191B', '#70597B', '#EBE4F4', '#F6EEF0'],
    typo: 'Super Sans VF, Super Serif VF, Super Sans Mono VF : polices maison',
    why: 'Un noir chaud (légèrement bordeaux) au lieu du noir bleuté habituel, avec un violet poudré et des lavandes douces. Le mélange de sans et de serif de marque donne un ton plus humain que les outils sombres classiques.',
    transposable: 'Noir chaud et accent violet sourd : une piste pour un thème sombre qui ne ressemble pas à Linear. Boîte mail très dépouillée, utile pour les deux colonnes de mails.',
    proof: 'Les utilisateurs saluent une interface « propre, belle, sans bouton ni icône parasite » (TechCrunch, 2017) ; la marque est un classique des références d’UI de productivité.',
    proofUrl: 'https://techcrunch.com/2017/08/18/rapportive-founders-new-startup-superhuman-is-what-gmail-would-be-if-built-today/',
  },
  {
    n: 15,
    id: 'superlist',
    family: 'sombre',
    name: 'Superlist',
    url: 'https://www.superlist.com/',
    image: '/demo/references/15-superlist.jpg',
    palette: ['#181826', '#372846', '#6F6A86', '#008ADB', '#F64C36'],
    typo: 'Inter et Inter Display, Haffer XH (titres)',
    why: 'Bleu nuit teinté de violet, avec un titre dont une moitié est en dégradé jaune orangé et un bouton rouge vif. Le sombre est plus coloré et plus chaleureux que le gris graphite.',
    transposable: 'Fonds bleu nuit teinté plutôt que graphite neutre ; un dégradé de couleur sur un seul mot du titre ; un bouton rouge réservé à l’action principale.',
    proof: '#1 Produit du jour sur Product Hunt (février 2024, 1,3 k votes) ; créé par l’équipe de Wunderlist, dont la communauté loue la conception sans encombrement.',
    proofUrl: 'https://www.androidcentral.com/apps-software/superlist-app-launch',
  },
  {
    n: 16,
    id: 'playdate',
    family: 'retro',
    name: 'Playdate (Panic)',
    url: 'https://play.date/',
    image: '/demo/references/16-playdate.jpg',
    palette: ['#788086', '#414141', '#F9D35F', '#FECD40', '#000000'],
    typo: 'Roobert',
    why: 'Un boîtier jaune vif sur gris acier, une manivelle, un écran noir et blanc : tout est assumé comme un objet, sans coins ultra arrondis ni verre. Le jaune est utilisé comme une couleur d’instrument, pas comme un accent web.',
    transposable: 'Un jaune d’avertissement sur gris acier pour les alertes et le trait « maintenant » ; boutons avec un vrai relief de touche plutôt que des aplats plats.',
    proof: 'Dessiné avec Teenage Engineering ; salué par Domus (« une Game Boy conçue pour l’ère Netflix ») et Creative Bloq (« la console portable la plus adorable »).',
    proofUrl: 'https://domusweb.it/en/design/gallery/2022/06/24/playdate-a-game-boy-designed-for-the-netflix-era.html',
  },
  {
    n: 17,
    id: 'te',
    family: 'retro',
    name: 'Teenage Engineering',
    url: 'https://teenage.engineering/',
    image: '/demo/references/17-te.jpg',
    palette: ['#FFFFFF', '#000000', '#F26435', '#BAB7B6', '#5A5858'],
    typo: 'TechnoType et polices pixel maison',
    why: 'Blanc, noir et un orange industriel, des pictogrammes dessinés au pixel, un titre énorme condensé : la grille d’un manuel d’instrument des années 80. C’est l’interface vue comme du matériel audio.',
    transposable: 'Mini-pictogrammes carrés pour les domaines, étiquettes en capitales mono, un orange de signalisation unique. Le style le plus « tableau de bord de voiture ».',
    proof: 'Plusieurs produits ont reçu des prix de design, dont le synthétiseur OP-1 (indiqué par la presse spécialisée comme Sound on Sound) ; je n’ai pas relevé de prix précis pour le site lui-même.',
    proofUrl: 'https://www.soundonsound.com/reviews/teenage-engineering-op-1-field',
  },
  {
    n: 18,
    id: 'nothing',
    family: 'retro',
    name: 'Nothing',
    url: 'https://fr.nothing.tech/',
    image: '/demo/references/18-nothing.jpg',
    palette: ['#000000', '#15161A', '#2D2E32', '#707072', '#C9C9C9', '#D71921'],
    typo: 'Ndot (matrice de points), NType 82, Geist, Lattera Mono',
    why: 'Noir total, trame de points discrète en fond, capitales en police point-matrice et un casque photographié comme une pièce de musée. Le rouge de marque n’apparaît que comme voyant.',
    transposable: 'Trame de points ou d’heures en fond de l’agenda, police à matrice de points pour l’heure courante, rouge utilisé uniquement comme voyant d’alerte (comme ton rouge Ferrari réservé).',
    proof: 'Red Dot 2023 (Phone (1) et son interface Glyph, Ear (stick), Ear (2)) puis Red Dot et iF en 2024, selon Nothing lui-même.',
    proofUrl: 'https://au.nothing.tech/blogs/news/red-dot-design-award',
  },
  {
    n: 19,
    id: 'mercury',
    family: 'matiere',
    name: 'Mercury',
    url: 'https://mercury.com/',
    image: '/demo/references/19-mercury.jpg',
    palette: ['#1B212D', '#2C343C', '#6F7889', '#9F9496', '#D8D2D0', '#5064EB'],
    typo: 'Tiempos Headline, Arcadia (maison), IBM Plex Mono',
    why: 'Une photographie de bureau dans la montagne, brumeuse, bleu nuit, avec un titre serif discret : la banque se présente comme un lieu calme, pas comme un tableau de chiffres. Le bouton bleu est le seul point vif.',
    transposable: 'Une photo ou texture floue de ciel ou de paysage en fond de l’écran de démarrage, serif pour les titres, bleu nuit chaud plutôt que gris pour le sombre.',
    proof: 'Cité pour un design de banque « pensé comme un logiciel » (analyse de 925 Studios) et pour sa carte lévitante avec reflet métallique ; aucun prix vérifié.',
    proofUrl: 'https://www.925studios.co/blog/mercury-design-breakdown',
  },
  {
    n: 20,
    id: 'stripepress',
    family: 'matiere',
    name: 'Stripe Press',
    url: 'https://press.stripe.com/',
    image: '/demo/references/20-stripepress.jpg',
    palette: ['#201819', '#4A363C', '#5B2134', '#7B5C44', '#938665', '#57605D'],
    typo: 'Ivar Headline, Ivar Text, Ivar Display',
    why: 'Un empilement de livres aux tranches de matières différentes (marbré, cuir, toile) sur fond brun prune : le site est une étagère. Les teintes bordeaux, olive et cuir sont sourdes et proches entre elles.',
    transposable: 'Le plus proche de tes palettes automobiles : bordeaux, cuir et vert sourd sur fond brun profond. Utile pour un thème sombre chaud, avec un serif de titre.',
    proof: 'Le site « Ideas for progress » figure dans la galerie Awwwards (niveau de distinction exact non vérifié) ; très cité comme modèle d’éditorial web.',
    proofUrl: 'https://www.awwwards.com/inspiration/stripe-press-ideas-for-progress-3',
  },
];
